In [135]:
# Importing Important Libaries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [136]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [137]:
# Import the Dataset
df = pd.read_csv('/content/processes2.csv')

In [138]:
df.shape

(2095, 14)

In [139]:
df.sample(10)

,Unnamed: 0,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,seats,max_power (in bph),Mileage Unit,Mileage,Engine (CC)
539,1638,Ford,2012,300000,90000,Diesel,Individual,Manual,First Owner,5,68.00,kmpl,20.00,1399
750,2316,Maruti,2011,114999,10000,Petrol,Individual,Manual,First Owner,5,46.30,kmpl,19.70,796
2071,6159,Tata,2013,190000,120000,Diesel,Individual,Manual,Second Owner,5,74.00,kmpl,22.30,1248
366,1138,Mahindra,2018,660000,74250,Diesel,Dealer,Manual,First Owner,7,74.96,kmpl,21.00,1498
734,2259,Maruti,2012,370000,60000,Diesel,Individual,Manual,First Owner,5,74.00,kmpl,22.90,1248
1285,3880,Maruti,2011,235000,60000,Petrol,Individual,Manual,First Owner,5,67.10,kmpl,20.92,998
1988,5921,Volkswagen,2012,380000,200000,Diesel,Individual,Manual,First Owner,5,103.60,kmpl,20.54,1598
720,2220,Hyundai,2017,280000,31000,Petrol,Individual,Manual,Second Owner,5,55.20,kmpl,21.10,814
2087,6239,Hyundai,2011,450000,128000,Diesel,Individual,Manual,Second Owner,5,126.32,kmpl,22.32,1582
1108,3372,Maruti,2017,650000,21000,Petrol,Individual,Manual,First Owner,5,81.80,kmpl,22.00,1197

In [140]:
df['Power'] = df['max_power (in bph)']

In [141]:
df.drop('max_power (in bph)',axis=1,inplace=True)

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2095 entries, 0 to 2094
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     2095 non-null   int64
 1   name           2095 non-null   object
 2   year           2095 non-null   int64
 3   selling_price  2095 non-null   int64
 4   km_driven      2095 non-null   int64
 5   fuel           2095 non-null   object
 6   seller_type    2095 non-null   object
 7   transmission   2095 non-null   object
 8   owner          2095 non-null   object
 9   seats          2095 non-null   int64
 10  Mileage Unit   2095 non-null   object
 11  Mileage        2095 non-null   float64
 12  Engine (CC)    2095 non-null   int64
 13  Power          2095 non-null   float64
dtypes: float64(2), int64(6), object(6)
memory usage: 229.3+ KB

In [143]:
df.describe()

,Unnamed: 0,year,selling_price,km_driven,seats,Mileage,Engine (CC),Power
count,2095.000000,2095.000000,2.095000e+03,2095.000000,2095.000000,2095.000000,2095.000000,2095.000000
mean,3155.537947,2014.052506,4.272799e+05,67413.593795,5.096897,21.397928,1205.078282,77.410427
std,1791.039215,3.273451,2.326698e+05,41580.846333,0.457000,1.209234,245.058696,19.884938
min,0.000000,2000.000000,4.595700e+04,1000.000000,4.000000,19.600000,624.000000,35.000000
25%,1589.500000,2012.000000,2.500000e+05,35000.000000,5.000000,20.360000,998.000000,67.040000
50%,3185.000000,2014.000000,3.900000e+05,60000.000000,5.000000,21.100000,1248.000000,74.000000
75%,4709.500000,2017.000000,5.555000e+05,90000.000000,5.000000,22.540000,1396.000000,88.730000
max,6256.000000,2020.000000,1.594000e+06,270000.000000,8.000000,23.590000,1598.000000,126.320000

In [144]:
print(df['selling_price'].describe())

count    2.095000e+03
mean     4.272799e+05
std      2.326698e+05
min      4.595700e+04
25%      2.500000e+05
50%      3.900000e+05
75%      5.555000e+05
max      1.594000e+06
Name: selling_price, dtype: float64

In [145]:
df.isnull().sum()

Unnamed: 0       0
name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
seats            0
Mileage Unit     0
Mileage          0
Engine (CC)      0
Power            0
dtype: int64

In [146]:
# Using Standard Scaler
scaler = StandardScaler()
df[['km_driven']] = scaler.fit_transform(df[['km_driven']])
df[['seats']] = scaler.fit_transform(df[['seats']])
df[['Mileage']] = scaler.fit_transform(df[['Mileage']])
df[['Engine (CC)']] = scaler.fit_transform(df[['Engine (CC)']])
df[['Power']] = scaler.fit_transform(df[['Power']])

In [147]:
# Using Label Encoder
le = LabelEncoder()
df['name'] = le.fit_transform(df['name'])
df['fuel'] = le.fit_transform(df['fuel'])
df['transmission'] = le.fit_transform(df['transmission'])

In [148]:
x = df[['km_driven','seats','Mileage','Engine (CC)','Power','name','fuel','transmission']]
y = df['selling_price']

In [149]:
x.head()

,km_driven,seats,Mileage,Engine (CC),Power,name,fuel,transmission
0,1.878390,-0.21208,1.656049,0.175191,-0.171549,5,1,1
1,1.433367,-0.21208,1.325182,0.779272,0.633272,3,1,1
2,-0.539165,-0.21208,-1.040518,-0.032973,0.223819,3,3,1
3,0.543322,-0.21208,1.813211,0.648660,-0.518628,8,1,1
4,2.443689,-0.21208,-1.156321,0.791517,-0.468327,1,1,1

In [150]:
y.head()

0    450000
1    225000
2    440000
3    350000
4    200000
Name: selling_price, dtype: int64

In [151]:
# Split the Train and Test data

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [152]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)

In [153]:
print('R2_score :-',r2_score(y_test,y_pred))
print('mean_squared_error :-',mean_squared_error(y_test,y_pred))
print('mean_absolute_error :-',mean_absolute_error(y_test,y_pred))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE:", rmse)

R2_score :- 0.6212985787294278
mean_squared_error :- 17901209057.52255
mean_absolute_error :- 100672.39947539735
RMSE: 133795.39998640667

In [154]:
from sklearn.linear_model import SGDRegressor
sgd = SGDRegressor(alpha=0.1,max_iter=1000)
sgd.fit(x_train,y_train)
y_pred = sgd.predict(x_test)

In [155]:
print('R2_score :-',r2_score(y_test,y_pred))
print('mean_squared_error :-',mean_squared_error(y_test,y_pred))
print('mean_absolute_error :-',mean_absolute_error(y_test,y_pred))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE:", rmse)

R2_score :- 0.604401731597387
mean_squared_error :- 18699922703.51004
mean_absolute_error :- 102117.1615672911
RMSE: 136747.66068752343

In [156]:
model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(x_train,y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [157]:
y_pred = model.predict(x_test)

In [158]:
print('R2_score :-',r2_score(y_test,y_pred))
print('mean_squared_error :-',mean_squared_error(y_test,y_pred))
print('mean_absolute_error :-',mean_absolute_error(y_test,y_pred))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE:", rmse)

R2_score :- 0.8302988232489639
mean_squared_error :- 8021771431.793532
mean_absolute_error :- 60444.18053974769
RMSE: 89564.34241255575

In [159]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [160]:
y_pred = model.predict(x_test)

In [161]:
print('R2_score :-',r2_score(y_test,y_pred))
print('mean_squared_error :-',mean_squared_error(y_test,y_pred))
print('mean_absolute_error :-',mean_absolute_error(y_test,y_pred))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE:", rmse)

R2_score :- 0.8408449292182922
mean_squared_error :- 7523258880.0
mean_absolute_error :- 59821.01171875
RMSE: 86736.72163507219

In [163]:
results = pd.DataFrame({
    'Model':[
        'Linear Regression',
        'SGD Regressor',
        'Random Forest',
        'XGBoost'
    ],
    'R2 Score':[0.62,0.61,0.81,0.84]
})

results.sort_values('R2 Score',ascending=False)

               Model  R2 Score
3            XGBoost      0.84
2      Random Forest      0.81
0  Linear Regression      0.62
1      SGD Regressor      0.61